default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jitips_development

test:
  <<: *default
  database: jitips_test

production:
  <<: *default
  database: jitips_production
  username: jitips
  password: <%= ENV['JITIPS_DATABASE_PASSWORD'] %>
